// Generated By protoc-gen-luabind.  DO NOT EDIT!
//

#include "luabind_pb_test.pb.h"

#include "luabind/luabind.hpp"
#include "luabind/enum.hpp"
#include "luabind/out_value_policy.hpp"

#include "scriptengine/luabind_register_manager.h"

luabind::scope Register_ETest() {
 return luabind::enum_("ETest").def() [
  luabind::value("kEnumTest_1", 1),
  luabind::value("kEnumTest_2", 2),
  luabind::value("kEnumTest_3", 3)
 ];
}


luabind::scope Register_MTest() {
 return luabind::class_< ::luabindpbtest::MTest, ::google::protobuf::Message, ::google::protobuf::MessageLite>("MTest")
  .def(luabind::constructor<>())
  .property("name", (const std::string& (::luabindpbtest::MTest::*)(void) const)&::luabindpbtest::MTest::name, (void (::luabindpbtest::MTest::*)(const char*))&::luabindpbtest::MTest::set_name)
  .property("value", (::google::protobuf::uint32 (::luabindpbtest::MTest::*)(void) const)&::luabindpbtest::MTest::value, (void (::luabindpbtest::MTest::*)(::google::protobuf::uint32))&::luabindpbtest::MTest::set_value);
}

luabind::scope Register_MTestList() {
 return luabind::class_< ::luabindpbtest::MTestList, ::google::protobuf::Message, ::google::protobuf::MessageLite>("MTestList")
  .def(luabind::constructor<>())
  .property("i_t", (::google::protobuf::uint32 (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::i_t, (void (::luabindpbtest::MTestList::*)(::google::protobuf::uint32))&::luabindpbtest::MTestList::set_i_t)
  .property("s_t", (const std::string& (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::s_t, (void (::luabindpbtest::MTestList::*)(const char*))&::luabindpbtest::MTestList::set_s_t)
  .property("b_t", (const std::string& (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::b_t, (void (::luabindpbtest::MTestList::*)(const char*))&::luabindpbtest::MTestList::set_b_t)
  .property("e_t", (::luabindpbtest::ETest (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::e_t, (void (::luabindpbtest::MTestList::*)(::luabindpbtest::ETest))&::luabindpbtest::MTestList::set_e_t)
  .def("one", (const ::luabindpbtest::MTest& (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::one)
  .def("mutable_one", (::luabindpbtest::MTest* (::luabindpbtest::MTestList::*)(void))&::luabindpbtest::MTestList::mutable_one)
  .def("i_all_size", (int (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::i_all_size)
  .def("add_i_all", (void (::luabindpbtest::MTestList::*)(::google::protobuf::uint32))&::luabindpbtest::MTestList::add_i_all)
  .def("i_all", (::google::protobuf::uint32 (::luabindpbtest::MTestList::*)(int) const)&::luabindpbtest::MTestList::i_all)
  .def("s_all_size", (int (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::s_all_size)
  .def("add_s_all", (void (::luabindpbtest::MTestList::*)(const char*))&::luabindpbtest::MTestList::add_s_all)
  .def("s_all", (const std::string& (::luabindpbtest::MTestList::*)(int) const)&::luabindpbtest::MTestList::s_all)
  .def("m_all_size", (int (::luabindpbtest::MTestList::*)(void) const)&::luabindpbtest::MTestList::m_all_size)
  .def("add_m_all", (::luabindpbtest::MTest* (::luabindpbtest::MTestList::*)(void))&::luabindpbtest::MTestList::add_m_all)
  .def("m_all", (const ::luabindpbtest::MTest& (::luabindpbtest::MTestList::*)(int) const)&::luabindpbtest::MTestList::m_all);
}

//////////////////////////////////////////////////
void LuabindPB_luabind_pb_test_RegisterAll() {
  LuabindRegisterManager::GetInstance()->RegisterLuabindMessage(&Register_ETest);
  LuabindRegisterManager::GetInstance()->RegisterLuabindMessage(&Register_MTest);
  LuabindRegisterManager::GetInstance()->RegisterLuabindMessage(&Register_MTestList);
}

//////////////////////////////////////////////////
